service: sandbox-sls-ws-ddb

frameworkVersion: ">=1.69.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  region: ap-northeast-1
  stage: v1
  websocketsApiName: serverless-ws
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body

  environment:
    CONNECTION_TABLE: ${self:custom.CONNECTION_TABLE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - Fn::Join:
            - ":"
            - - arn:aws:dynamodb
              - ${self:provider.region}
              - Ref: "AWS::AccountId"
              - table/${self:custom.CONNECTION_TABLE}
        - Fn::Join:
            - ":"
            - - arn:aws:dynamodb
              - ${self:provider.region}
              - Ref: "AWS::AccountId"
              - table/${self:custom.CONNECTION_TABLE}/index/liveId-index

custom:
  CONNECTION_TABLE: campusonair-connection-table

package:
  exclude:
    - .circleci/**
    - .git/**
    - bin/**
    - test/**
    - docs/**
    - .*
    - package-lock.json
    - yarn.lock
    - README.md

functions:
  connect:
    handler: src/connect.handler
    events:
      - websocket: $connect

  disconnect:
    handler: src/disconnect.handler
    events:
      - websocket: $disconnect

  default:
    handler: src/default.handler
    events:
      - websocket: $default

  listLive:
    handler: src/lives/listLive.handler
    events:
      - http:
          path: lives
          method: get
          integration: lambda-proxy
          cors:
            origin: "*"

  createLive:
    handler: src/lives/createLive.handler
    events:
      - http:
          path: live
          method: post
          integration: lambda-proxy
          cors:
            origin: "*"

  getLive:
    handler: src/lives/getLive.handler
    events:
      - http:
          path: live/{liveId}
          method: get
          integration: lambda-proxy
          cors:
            origin: "*"

  updateLive:
    handler: src/lives/updateLive.handler
    events:
      - http:
          path: live/{liveId}
          method: put
          integration: lambda-proxy
          cors:
            origin: "*"

  deleteLive:
    handler: src/lives/deleteLive.handler
    events:
      - http:
          path: live/{liveId}
          method: delete
          integration: lambda-proxy
          cors:
            origin: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
